server:
  port: 8090
spring:
  application:
    name: postinger-identity-service
  main:
    web-application-type: servlet
  datasource:
    url: jdbc:postgresql://161.35.77.124:25433/postinger_omer
    username: root
    password: a*O5Fz455b
    driverClassName: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    hibernate:
      ddl-auto: update



postinger:
  app:
    secret: postinger

app:
  expires:
    in: 604800

